# Generated by Django 3.0.5 on 2020-04-20 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0002_league_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='league_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='leagues.League'),
        ),
    ]
