# Generated by Django 3.0.5 on 2020-04-20 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0003_game_league_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='games_played',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='points',
            field=models.IntegerField(null=True),
        ),
    ]
