# Generated by Django 3.0.5 on 2020-04-20 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0004_auto_20200420_1747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='game_name',
        ),
    ]
