# Generated by Django 3.0.5 on 2020-04-21 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0008_auto_20200420_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='sport_type',
            field=models.CharField(default='No Sport', max_length=50),
        ),
    ]
